"""create new tables

Revision ID: 39df96f125af
Revises: 
Create Date: 2023-03-03 19:13:45.280178

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "39df96f125af"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modelname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("precision", sa.Float(), nullable=False),
        sa.Column("recall", sa.Float(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("auc", sa.Float(), nullable=False),
        sa.Column("f1", sa.Float(), nullable=False),
        sa.Column("time", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trainingqueue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predict",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prediction", sa.Boolean(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("predict")
    op.drop_table("trainingqueue")
    op.drop_table("model")
    # ### end Alembic commands ###
